
# turn segmented_files into materials according to the file name
segmented_files2materials = {
    'spleen': 'soft tissue',
    'kidney_right': 'soft tissue',
    'kidney_left': 'soft tissue',
    'gallbladder': 'soft tissue',
    'liver': 'soft tissue',
    'stomach': 'soft tissue',
    'pancreas': 'soft tissue',
    'adrenal_gland_right': 'soft tissue',
    'adrenal_gland_left': 'soft tissue',
    'lung_upper_lobe_left': 'soft tissue',
    'lung_lower_lobe_left': 'soft tissue',
    'lung_upper_lobe_right': 'soft tissue',
    'lung_middle_lobe_right': 'soft tissue',
    'lung_lower_lobe_right': 'soft tissue',
    'esophagus': 'soft tissue',
    'trachea': 'soft tissue',
    'thyroid_gland': 'soft tissue',
    'small_bowel': 'soft tissue',
    'duodenum': 'soft tissue',
    'colon': 'soft tissue',
    'urinary_bladder': 'soft tissue',
    'prostate': 'soft tissue',
    'kidney_cyst_left': 'soft tissue',
    'kidney_cyst_right': 'soft tissue',
    'sacrum': 'bone',
    'vertebrae_S1': 'bone',
    'vertebrae_L5': 'bone',
    'vertebrae_L4': 'bone',
    'vertebrae_L3': 'bone',
    'vertebrae_L2': 'bone',
    'vertebrae_L1': 'bone',
    'vertebrae_T12': 'bone',
    'vertebrae_T11': 'bone',
    'vertebrae_T10': 'bone',
    'vertebrae_T9': 'bone',
    'vertebrae_T8': 'bone',
    'vertebrae_T7': 'bone',
    'vertebrae_T6': 'bone',
    'vertebrae_T5': 'bone',
    'vertebrae_T4': 'bone',
    'vertebrae_T3': 'bone',
    'vertebrae_T2': 'bone',
    'vertebrae_T1': 'bone',
    'vertebrae_C7': 'bone',
    'vertebrae_C6': 'bone',
    'vertebrae_C5': 'bone',
    'vertebrae_C4': 'bone',
    'vertebrae_C3': 'bone',
    'vertebrae_C2': 'bone',
    'vertebrae_C1': 'bone',
    'heart': 'soft tissue',
    'aorta': 'soft tissue',
    'pulmonary_vein': 'soft tissue',
    'brachiocephalic_trunk': 'soft tissue',
    'subclavian_artery_right': 'soft tissue',
    'subclavian_artery_left': 'soft tissue',
    'common_carotid_artery_right': 'soft tissue',
    'common_carotid_artery_left': 'soft tissue',
    'brachiocephalic_vein_left': 'soft tissue',
    'brachiocephalic_vein_right': 'soft tissue',
    'atrial_appendage_left': 'soft tissue',
    'superior_vena_cava': 'soft tissue',
    'inferior_vena_cava': 'soft tissue',
    'portal_vein_and_splenic_vein': 'soft tissue',
    'iliac_artery_left': 'soft tissue',
    'iliac_artery_right': 'soft tissue',
    'iliac_vena_left': 'soft tissue',
    'iliac_vena_right': 'soft tissue',
    'humerus_left': 'bone',
    'humerus_right': 'bone',
    'scapula_left': 'bone',
    'scapula_right': 'bone',
    'clavicula_left': 'bone',
    'clavicula_right': 'bone',
    'femur_left': 'bone',
    'femur_right': 'bone',
    'hip_left': 'bone',
    'hip_right': 'bone',
    'spinal_cord': 'soft tissue',
    'gluteus_maximus_left': 'soft tissue',
    'gluteus_maximus_right': 'soft tissue',
    'gluteus_medius_left': 'soft tissue',
    'gluteus_medius_right': 'soft tissue',
    'gluteus_minimus_left': 'soft tissue',
    'gluteus_minimus_right': 'soft tissue',
    'autochthon_left': 'soft tissue',
    'autochthon_right': 'soft tissue',
    'iliopsoas_left': 'soft tissue',
    'iliopsoas_right': 'soft tissue',
    'brain': 'soft tissue',
    'skull': 'bone',
    'rib_left_1': 'bone',
    'rib_left_2': 'bone',
    'rib_left_3': 'bone',
    'rib_left_4': 'bone',
    'rib_left_5': 'bone',
    'rib_left_6': 'bone',
    'rib_left_7': 'bone',
    'rib_left_8': 'bone',
    'rib_left_9': 'bone',
    'rib_left_10': 'bone',
    'rib_left_11': 'bone',
    'rib_left_12': 'bone',
    'rib_right_1': 'bone',
    'rib_right_2': 'bone',
    'rib_right_3': 'bone',
    'rib_right_4': 'bone',
    'rib_right_5': 'bone',
    'rib_right_6': 'bone',
    'rib_right_7': 'bone',
    'rib_right_8': 'bone',
    'rib_right_9': 'bone',
    'rib_right_10': 'bone',
    'rib_right_11': 'bone',
    'rib_right_12': 'bone',
    'sternum': 'bone',
    'costal_cartilages': 'soft tissue'
}
